### PR TITLE
Split dovecot config into multiple files

### PR DESCRIPTION
**Pull request by jeroenrnl**
This is a fix for issue #31 

The resulting configuration is line-for-line identical to the original configuration, but now spread over multiple files, making extending and editing the config much easier.

I did remove the majority of comments, they can still be found in the .bak files once the server is running.

### CODE REVIEW

**Comment by technicalguru** [comment]
Hello @jeroenrnl - just checking your change. Give me a few more days to review and test it on my test mail instance. I plan to publish it along with 3.7.9.1 release (which also will have your SASL change)

**Comment by technicalguru** [comment]
Hello @jeroenrnl  - after analyzing your changes, I noted 2 mismatches from original configuration:

### inet_listener_imap is missing
The previous version had this code snippet

```
service imap-login {
    inet_listener imap {
        port = 143
    }
}
```
Why was it removed? My test instance still sems to work correctly. But I am not sure that this would be ok this way.

### Two additional sections:
A new service was added:

```
service submission-login {
  inet_listener submission {
     port = 587
  }
}
```
and

```
service pop3-login {
  inet_listener pop3-login {
     port = 995
     ssl = yes
  }
}
```
Was there a reason to include them?

**Comment by jeroenrnl** [comment]
@technicalguru to be honest, I'm not entirely sure anymore. It could be because they are the defaults, it could also have been oversights from me, or some of my personal configuration.
As far as I recall I compared the output of `doveconf` before and after my change and finetuned it until it was exactly equal, that would suggest they were part of the default config, but I can't be sure anymore.

**Comment by jeroenrnl** [comment]
@technicalguru I checked the output of `doveconf` on my system (I haven't updated to your latest version, but am still running my own version) and it includes the section for `inet_listener imap { }`, so I suppose it's indeed part of the default config.

**Comment by technicalguru** [comment]
Can you paste the output here so I can also verify against latest version? Thank you!

**Comment by jeroenrnl** [comment]
```
service imap-login {
  chroot = login
  client_limit = 0
  drop_priv_before_exec = no
  executable = imap-login
  extra_groups = 
  group = 
  idle_kill = 0
  inet_listener imap {
    address = 
    haproxy = no
    port = 143
    reuse_port = no
    ssl = no
  }
  inet_listener imaps {
    address = 
    haproxy = no
    port = 993
    reuse_port = no
    ssl = yes
  }
  privileged_group = 
  process_limit = 0
  process_min_avail = 0
  protocol = imap
  service_count = 1
  type = login
  user = $default_login_user
  vsz_limit = 18446744073709551615 B
}
```

**Pull request merged**
